services:
  app:
    container_name: lar12_app_local
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "9000:9000"
      - "6006:6006"
    volumes:
      - ./src:/var/www
    networks:
      - laravel-production
    depends_on:
      - db
      - redis

  nginx:
    container_name: lar12_nginx_local
    tty: true
    build:
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel-production

  db:
    container_name: lar12_db_local
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - laravel-production

  redis:
    container_name: lar12_redis_local
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - laravel-production

networks:
  laravel-production:

volumes:
  mysqldata:
